apiVersion: apps/v1
kind: Deployment
metadata:
  name: maawefk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maawefk
  template:
    metadata:
      labels:
        app: maawefk
    spec:
      containers:
      - image: okteto.dev/maawefk:latest
        name: maawefk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3a13d22c-fc28-4171-9f94-6fdfb26470c4"
        - name: Vless_Path
          value: "/vl5dted"
        - name: Vmess_UUID
          value: "3a13d22c-fc28-4171-9f94-6fdfb26470c4"
        - name: Vmess_Path
          value: "/vmddg45"
        - name: Share_Path
          value: "/v2link"
